### ISSUE TITLE
The WIndows open too much which can slow down your computers

### ISSUE THREAD

**Issue by changchengdouletmedia** [changcheng967/Online-Go.com-Account-Generator#1]
The WIndows open too much which can slow down your computers

**Comment by changcheng967** [comment]
Thank you for reaching us, we'll work on that

**Comment by changcheng967** [comment]
did you check the https://github.com/changcheng967/Online-Go.com-Account-Generator/releases/tag/v1.1.0_Alpha release? you can change the "max-workers" variable to make it lower,

**Comment by changcheng967** [comment]
hope that solves your problem

**Comment by changchengdouletmedia** [comment]
yeah but how do I know how many should I get

**Comment by changcheng967** [comment]
For a normal computer, it would be 2-5

**Comment by changchengdouletmedia** [comment]
Ok, thank you!

**Comment by changchengdouletmedia** [comment]
OK, Thank you

**Comment by changcheng967** [comment]
Oh I see I'll adjust it

**Comment by changcheng967** [comment]
done finished, see if it still exist
